import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import honeyPic from "../../public/images/profile/honey.jpg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import linkarrowUrl from "../../public/images/svgs/external-link.svg?url";
import styles from "../styles/index.module.css";
import Footer from "@/components/Footer";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Honey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full">
            <div className="w-full flex flex-col item-center self-center">
              <AnimatedText
                text="In Science We Trust."
                className={`mt-16 ${styles.maintext} capitalize xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:text-3xl`}
              />
              <p className="mt-8 text-xl lg:text-lg sm:text-sm font-medium flex justify-center ">
                Hi there, this is Honey, a front-end developer.
              </p>
              <div className="flex items-center justify-center mt-4 lg:self-center">
                <Link
                  href="https://mail.google.com/mail/u/0/#sent?compose=DmwnWsLLkgqBFQLWTFzHLdzDBrvKzTCxVlwFdbTPSRblPLmBfMFxxzmGzlPHfWkClfxCJvDpwrml"
                  target={"_blank"}
                  className="flex mx-6 mt-6 items-center  p-2.5 md:p-2 px-6 rounded-lg text-xl lg:text-lg sm:text-sm font-semibold border-2 border-solid border-dark hover:bg-dark hover:text-light dark:border-light dark:hover:bg-light dark:hover:text-dark"
                >
                  Contact me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
  //d
}
